# Jekyll Theme
theme: jekyll-theme-minimal

# Site Title
title: Smokey027's Personal Site

# Site Description
description: Welcome to my personal webpage, showcasing my projects and interests.

# Base URL
baseurl: "" # Use this if your site is hosted at the root of your domain.

# Site URL
url: "https://smokey027.github.io" # Replace with your actual site URL.

